name: keystore deploy apps via SSH

on:
  workflow_run:
    workflows: ["keystore-backend CI/CD", "keystore-frontend CI/CD"]
    branches: [ main ]
    types:
      - completed

env:
  REGISTRY: docker.io
  FRONTEND_IMAGE_NAME: keystore-frontend
  BACKEND_IMAGE_NAME: keystore-backend

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/KeyStore
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            docker-compose down
            docker-compose -f /srv/KeyStore/docker-compose.yaml up -d